version: '1.0'
services:
  smart.service:
    image: smart.service:latest
    container_name: smart.service
    networks:
      - smart-server-network
    build:
      context: ./smart-service/
      dockerfile: Dockerfile
    ports:
      - "8180:8180"
    expose:
      - "8180"
    restart: always
    environment:
      - SERVER_PORT= 8180

networks:
  smart-server-network:
    driver: bridge